name: azureml-training
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - nltk=3.7
  - numpy=1.24.3
  - pandas=1.2.5
  - python-dotenv=1.0.0
  - scikit-learn=1.1.3
  # - mlflow=2.5.0
  - pip:
      - 'azureml-dataset-runtime[pandas,fuse]'
      - azureml-defaults==1.52.0
