services:
  api:
    # It seems like it doesn't like to use my MacBook, as this image was created on a Linux machine...
    # I can't seem to test it on this machine, but will test it later on another PC, in another recording
    image: ghcr.io/koenraadva/mro-class
    ports:
      - "8000:80"
    # In case we want to have another Python script to be executed (because we made a small mistake using the Model name ...
    volumes:
      - ./api/main.py:/code/main.py